### ISSUE TITLE
Which font are you using in the demo?

### ISSUE THREAD

**Issue by thomasabishop** [Murderlon/cyberpunk-iterm#1]
Love the theme. Sorry to create a non-issue but I'd be grateful if you could let me know the font you are using in the demo. Thank you.

**Comment by Murderlon** [comment]
Thanks, and no problem! The font is the free and customizable [Input Mono](http://input.fontbureau.com/). Though [Iosevka](https://typeof.net/Iosevka/) is my new favorite.

**Comment by thomasabishop** [comment]
Many thanks indeed!
