### ISSUE TITLE
Missing the colour

### ISSUE THREAD

**Issue by arkilis** [Murderlon/cyberpunk-iterm#4]
Thanks for making this, looks pretty cool, followed the steps but missing the colours:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/1528028/85017950-ad1d6780-b1af-11ea-99fe-a65cc1308e8a.png">

**Comment by cgiax** [comment]
@arkilis you can use 'exa' instead for 'ls'. You can find exa [here](https://the.exa.website/introduction).

Then simply create an alias in your shell if you don't like using exa, eg: 'exa -al'
