### ISSUE TITLE
Add to Ubuntu Terminal

### ISSUE THREAD

**Issue by GeorgeD88** [Murderlon/cyberpunk-iterm#5]
How do I add this to the Ubuntu (linux) terminal?

**Comment by Murderlon** [comment]
You can contribute the colorscheme if you'd like. For example, bluloco adds it for most terminals: https://github.com/uloco/bluloco.nvim/tree/main/terminal-themes.

**Comment by GeorgeD88** [comment]
This is probably stupid because your sentence is very simple, but I'm not sure what you mean?

**Comment by Murderlon** [comment]
Every terminal has it's own config syntax to use colorschemes. This one is specifically and only for iTerm on macOS. I'm not entirely sure how you make one for gnome-terminal, which is what Ubuntu uses. Catppuccin uses a script for it: https://github.com/catppuccin/gnome-terminal/blob/main/install.py. But surely it should also be possible with a static file.

**Comment by GeorgeD88** [comment]
sounds good, thank you! I was thinking of making the theme myself but we get 2 rows of colors instead of your 1 row, and there's so many color things that I just got overwhelmed with having to match everything, because I don't know what to put for all the extra colors outside of the standard row lol. but yeah I think I'll do that. can you provide me with all the color codes you used? and if I showed you the screen of color customizations, would you be able to clear up what I need for the extra ones?

**Comment by GeorgeD88** [comment]
I was able to figure it out! It took a ton of work, but it was very worth it. I found a script that converted iTerm to gnome-terminal theme, which helped a lot, but didn't fully do it. So I spent a bit of time messing with the theme file and setting, and fixing parts to match yours, and I got this in the end!! I'll put it on GitHub tomorrow with a little guide on the command to import it, and maybe you can mention my repo as the linux version for people to use.
![Screenshot from 2023-04-22 02-52-24](https://user-images.githubusercontent.com/44484311/233768221-4dda3247-0af7-4ade-bcb6-647471ab5b8f.png)
